{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kestra.plugin",
    "module": "plugin-rest-server",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-rest-server-1.3.0.jar",
          "url": "plugin-rest-server-1.3.0.jar",
          "size": 7203221,
          "sha512": "c93b78e50fde956d34e949e1ed397d39378da90496d5fedca08c65bd8f07628e8d36d3ba37dc8bc33435aef641f098b3c94b3182cee20a52234f69195670a884",
          "sha256": "01707579d8ff139a9f1e3d07c36b8f2e8d5f2adde95d12e3f23cc657f14d1f62",
          "sha1": "563bf19c129c21cfbe5e6b7a801fb7e88269e4ae",
          "md5": "34b3f5eca88ff5192fb30fbf888510fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.kestra",
          "module": "platform",
          "version": {
            "strictly": "1.3.28",
            "requires": "1.3.28"
          },
          "attributes": {
            "org.gradle.category": "enforced-platform"
          }
        },
        {
          "group": "io.javalin",
          "module": "javalin",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-rest-server-1.3.0.jar",
          "url": "plugin-rest-server-1.3.0.jar",
          "size": 7203221,
          "sha512": "c93b78e50fde956d34e949e1ed397d39378da90496d5fedca08c65bd8f07628e8d36d3ba37dc8bc33435aef641f098b3c94b3182cee20a52234f69195670a884",
          "sha256": "01707579d8ff139a9f1e3d07c36b8f2e8d5f2adde95d12e3f23cc657f14d1f62",
          "sha1": "563bf19c129c21cfbe5e6b7a801fb7e88269e4ae",
          "md5": "34b3f5eca88ff5192fb30fbf888510fc"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-rest-server-1.3.0.jar",
          "url": "plugin-rest-server-1.3.0.jar",
          "size": 7203221,
          "sha512": "c93b78e50fde956d34e949e1ed397d39378da90496d5fedca08c65bd8f07628e8d36d3ba37dc8bc33435aef641f098b3c94b3182cee20a52234f69195670a884",
          "sha256": "01707579d8ff139a9f1e3d07c36b8f2e8d5f2adde95d12e3f23cc657f14d1f62",
          "sha1": "563bf19c129c21cfbe5e6b7a801fb7e88269e4ae",
          "md5": "34b3f5eca88ff5192fb30fbf888510fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-rest-server-1.3.0-sources.jar",
          "url": "plugin-rest-server-1.3.0-sources.jar",
          "size": 19423,
          "sha512": "fa6346c1d2c5281c68f10aa8969842c8fc8e5c111d92c42dc9618c2dcdc250a5087784497c677ca9c69206777f6fa3ebca9aa5e8da4121e8a3055fc90704ef46",
          "sha256": "4b748cb7776ddafb6c232fb0a025f074bc040ccf3fe7db84a6dba21f3868175c",
          "sha1": "30c5a9c2757e66762dab31f80a39491ae0a13fcd",
          "md5": "887a60f51041a6f2ae63ede58d9bd957"
        }
      ]
    }
  ]
}
