{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kestra.plugin",
    "module": "plugin-rest-server",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-rest-server-1.4.0.jar",
          "url": "plugin-rest-server-1.4.0.jar",
          "size": 7211539,
          "sha512": "b9b302a478fcc115879dbbce2b451fc8dfc565a13cb21b40051dcbf9cd90417247db5f9905388fb0ed9090379cfa4d2690e12f8b2491cf48e8dfdde5ab2e51c4",
          "sha256": "b24ea3cd0db36ff734efdf6480b1ae9d2a52d9db33d29df191deaf33a65116f5",
          "sha1": "ed46ea2dc2532fe1d7354ce30195c1549e94561b",
          "md5": "8312cca8e9927b7b0ea8040e1ac6af83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.kestra",
          "module": "platform",
          "version": {
            "strictly": "1.3.28",
            "requires": "1.3.28"
          },
          "attributes": {
            "org.gradle.category": "enforced-platform"
          }
        },
        {
          "group": "io.javalin",
          "module": "javalin",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-rest-server-1.4.0.jar",
          "url": "plugin-rest-server-1.4.0.jar",
          "size": 7211539,
          "sha512": "b9b302a478fcc115879dbbce2b451fc8dfc565a13cb21b40051dcbf9cd90417247db5f9905388fb0ed9090379cfa4d2690e12f8b2491cf48e8dfdde5ab2e51c4",
          "sha256": "b24ea3cd0db36ff734efdf6480b1ae9d2a52d9db33d29df191deaf33a65116f5",
          "sha1": "ed46ea2dc2532fe1d7354ce30195c1549e94561b",
          "md5": "8312cca8e9927b7b0ea8040e1ac6af83"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-rest-server-1.4.0.jar",
          "url": "plugin-rest-server-1.4.0.jar",
          "size": 7211539,
          "sha512": "b9b302a478fcc115879dbbce2b451fc8dfc565a13cb21b40051dcbf9cd90417247db5f9905388fb0ed9090379cfa4d2690e12f8b2491cf48e8dfdde5ab2e51c4",
          "sha256": "b24ea3cd0db36ff734efdf6480b1ae9d2a52d9db33d29df191deaf33a65116f5",
          "sha1": "ed46ea2dc2532fe1d7354ce30195c1549e94561b",
          "md5": "8312cca8e9927b7b0ea8040e1ac6af83"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-rest-server-1.4.0-sources.jar",
          "url": "plugin-rest-server-1.4.0-sources.jar",
          "size": 25054,
          "sha512": "e035d33b3294a7e9e5715e9c449e06f1913e2e432adea747914bf99623bd207d1b9fae8bbe6a425b7c8f842a8169141271528d0784bbac014f55413e465d6f23",
          "sha256": "79e1cc8a006d06c4e9f98aa8d0b2996da385252aaa7adcb34a3f495dccae0eaa",
          "sha1": "8913715360abc1220dff4b8befbfd10bb4a36da8",
          "md5": "a7f01262fb48f7cdffa186376f17e312"
        }
      ]
    }
  ]
}
